### ISSUE TITLE
[devops] 프론트엔드 develop 브랜치 생성

### ISSUE THREAD

**Issue by koreanddinghwan** [42-pingpong/frontend#1]

**Comment by koreanddinghwan** [comment]
해...주세요 프론트 레포지토리에 develop 브랜치에 기본적인 리액트 cra생성해주세여

**Comment by obvoso** [comment]
내일 가서 해도 되 나요

**Comment by koreanddinghwan** [comment]
> 내일 가서 해도 되 나요

어디신데요

**Comment by obvoso** [comment]
학교앞술집 집가서 생각나면 꼭 할게요..

2023년 7월 11일 (화) 오후 10:14, Myukang ***@***.***>님이 작성:

**Comment by koreanddinghwan** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ술도 못마시믄서...내일 인셉션 평가 중간중간해주세요~

**Comment by obvoso** [comment]
네ㅡ감사합니다^^
2023년 7월 11일 (화) 오후 10:19, Myukang ***@***.***>님이 작성:
