### ISSUE TITLE
fakeAuth사용법

### ISSUE THREAD

**Issue by koreanddinghwan** [42-pingpong/frontend#38]
<img width="1076" alt="Screen Shot 2023-08-03 at 3 27 17 AM" src="https://github.com/42-pingpong/frontend/assets/76278794/cbb634de-5128-4c2e-9886-7a138e79a1cb">

npm run seed하시면 기본적으로 10명의 가짜유저, 긜고 4명의 실제유저(저희)가 있슴다  
url보시면  

<img width="284" alt="Screen Shot 2023-08-03 at 3 27 54 AM" src="https://github.com/42-pingpong/frontend/assets/76278794/a674575a-8635-4e1a-b129-542e02edee17">  

요거와 같이 브라우저에 복붙하면 fakeAuth로 가상의 access token을 생성해서 실제 auth처럼 accessToken을 달고 보내드립니다.

**Comment by obvoso** [comment]
동작 확인 했습니다~~

@jinaji 
동작 확인 해보시려면 환경변수에서 /api빼시거나, 
리엑트 내에서 uri에 /api붙어있는 거 지워주시면 동작해욤
