### ISSUE TITLE
fix: DTO 수정요청

### ISSUE THREAD

**Issue by koreanddinghwan** [42-pingpong/frontend#53]
## 현재 전송되는 데이터

<img width="325" alt="스크린샷 2023-08-08 16 03 22" src="https://github.com/42-pingpong/frontend/assets/76278794/23197c20-950d-41d9-910c-17e37bfe7ab4">

https://github.com/42-pingpong/frontend/blob/577a894e3142343d404ce25fcc649ae60d4d5f7d/src/component/Chat/CreateChattingRoomModal.tsx#L26-L36

------------------------

1. currentParticipants=>삭제
2. maxParticipants => 숫자로

```typescript
{
  "chatName": "트센 채팅방",
  "password": "1234",
  "levelOfPublicity": "Priv",
  "maxParticipants": 10,
  "ownerId": 1
}
```

**Comment by jinaji** [comment]
1. 현재 참여인원 채팅방 리스트들 띄울 때 값 필요한데 (2/4 이런 식) 프론트로 넘겨주는 형식 저거랑 다른 건가여? userList 있는 식으로?
별개의 질문: 저 DTO 스웨거에서 모양 확인했었는데 제가 임의로 정보값 필요한 거 (현재 참여인원같은거) 추가해서 넘기면 곤란해지나요?
2. 확인했습니다~

제가 지금 밖이라 내일 클러가서 수정해도 될까여!!!

**Comment by koreanddinghwan** [comment]
> 

1-1 다릅니당 필요하신게 있으시면 말씀해주시면됩니당당
1-2 별개-> 곤란해집니당 없는 값 넘기면 서버에서 validation fail띄우면서 400던져용
2. 감사함둥

**Comment by koreanddinghwan** [comment]
만약에 채팅방 만들때 인원 초대한 상태로 만드시고싶다면 그렇게 api만들어놓을까여

**Comment by jinaji** [comment]
위에거 확인했구
요거 가능한가유? 그럼 저희가 정보 보낼 때 초대한 멤버 있을 때 멤버들 보내야 하는 거 아닌가여? 네스트도 옵셔널 있나용
