### ISSUE TITLE
chatting un 기능 관련 질문

### ISSUE THREAD

**Issue by obvoso** [42-pingpong/frontend#68]
unmute, unblock등의 소켓 이벤트를 어디 배치해야할지 모르겠어 요...
채팅 관련된 기능들 모두 un 기능까지 있으면 채팅 페이지 안에 컴포넌트 하나 추가해서 관리해야할까요?

지금은 채팅페이지에 채팅섹션에서 오른쪽 마우스 클릭하면 권한에 따라 ban, mute, kick등을 할 수 있어요

이전에 클라이언트에서 인메모리로 관리 안하고 밴 먹은 유저가 채팅방에 접근하려하면 서버에서 쳐낸다고 한 거 같은데
그러면 unban같은 걸 어디서 해야할까요..?

**Comment by koreanddinghwan** [comment]
지금 어떻게처리하고계신여

**Comment by koreanddinghwan** [comment]
식사하시고 슬랙콜로 ㄱㄱ

**Comment by obvoso** [comment]
지금 가능하신지
