### ISSUE TITLE
alarm

### ISSUE THREAD

**Issue by obvoso** [42-pingpong/frontend#81]
지금 예상되는데, 

```ts
      StatusSocket.on('alarms', saveNotificationList);
      StatusSocket.on('accept-friend', saveNotiResultList);
      StatusSocket.on('request-friend-from-user', saveNotificationList);
```

여기서

```ts
StatusSocket.on('alarms', saveNotificationList);
StatusSocket.on('request-friend-from-user', saveNotificationList);
```

하나는 배열을 받는 이벤트고, 다른 하나는 단순 request 1개를 받는 이벤트 잖아요? 근데 지금 1개의 callback이 이 경우 두개를 모두 처리하려고 해서 문제가 발생하는 것 같아요.

```ts
StatusSocket.on('request-friend-from-user', saveNotificationList);
```
이거는 단순 noti 1개만 처리할 수 있게하고,

<br>

```ts
StatusSocket.on('alarms', saveNotificationList);
```
이건 배열 처리할 수 있게 하는 콜백이 따로 있어야할것같은데요

_Originally posted by @koreanddinghwan in https://github.com/42-pingpong/frontend/pull/80#discussion_r1321063771_

**Comment by koreanddinghwan** [comment]
> 

alarms는 사용중이신

```ts
export interface ResponseNotificationDto {
  requestId: number;
  requestingUser: {
    id: number;
    nickName: string;
  };
  requestType: string;
  isAccepted: string;
  createdAt: string;
  pastTime: string;
}
```

이거 배열로 던져드릴께요

**Comment by obvoso** [comment]
아리가또입니다

**Comment by koreanddinghwan** [comment]
> > 
> 
> alarms는 사용중이신
> 
> ```ts
> export interface ResponseNotificationDto {
>   requestId: number;
>   requestingUser: {
>     id: number;
>     nickName: string;
>   };
>   requestType: string;
>   isAccepted: string;
>   createdAt: string;
>   pastTime: string;
> }
> ```
> 
> 이거 배열로 던져드릴께요

서버쪽 문제같은데

**Comment by obvoso** [comment]
롸

**Comment by koreanddinghwan** [comment]
> 롸

고침 pr날릴게요 이전에 sonarqube에서 하지말라는거 고쳤더니만 그게 문제였었네
